language: node_js

os:
  - linux
  - osx
  - windows

# https://github.com/nodejs/Release#nodejs-release-working-group
node_js:
  - 10
  - 12
  - 13

addons:
  snaps:
    - name: dotnet-runtime-31
      confinement: devmode

script:
  - npm run lint
  - npm test

notifications:
  email: false
